mysite/fantasybakeoff/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
 url(r'^league/(?P<id>\d+)/$', views.league_view, name='detail'),
 url(r'^create/$', views.team_create, name='create'), #create the team
 url(r'^index/$', views.team_detail, name='home'), #main home function
 url(r'^edit/$', views.team_update, name='update'), #make team changes
 url(r'^league-create/$', views.league_create, name='createLeague'), #create the team
 url(r'^league-add/$', views.league_add, name='leagueadd'), 
 url(r'^', views.homeview, name='base'), #main home function
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('fantasybakeoff.urls', namespace='fbo')),
    ]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
 url(r'^create/$', views.post_create, name='create'),
 url(r'^(?P<id>\d+)/$', views.post_detail, name='detail'),
 url(r'^list/$', views.post_list, name='list'),
 url(r'^(?P<id>\d+)/edit/$', views.post_update, name='update'),
 url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='delete'),
 url(r'^howto/$', views.howto, name='howto'),
]

mysite/posts/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Post(models.Model):
	title   = models.CharField(max_length=100)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={'id': self.id})

mysite/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ["title","content"]

mysite/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from .models import Post
from .forms import PostForm
# Create your views here.

def post_create(request):
	form = PostForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request,'Successfully Created')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {'form':form,}	
	return render(request,'post_form.html',context)
	

def post_detail(request, id=None):
	instance = get_object_or_404(Post, id=id)
	context = {"title": "detail",
		   "instance": instance
	}	
	return render(request,'post_detail.html',context)

def post_list(request):
	queryset = Post.objects.all()
	context = {'object_list': queryset,
		   'title': 'list'
	}

	return render(request,'post_list.html',context)

def post_update(request, id=None):
	instance = get_object_or_404(Post, id=id)
	form = PostForm(request.POST or None, instance=instance)
	if form.is_valid():	
		instance = form.save(commit=False)
		instance.save()
		messages.success(request,'Saved')
		return HttpResponseRedirect(instance.get_absolute_url())
	
	context = {"title": "detail",
		   "instance": instance,
		   "form": form,
	}	
	return render(request,'post_form.html',context)

def post_delete(request, id=None):
	instance = get_object_or_404(Post, id=id)
	instance.delete()
	messages.success(request,"Deleted")	

	return redirect("posts:list")

def howto(request):
	return render(request, 'howto.html')

mysite/templates/base.html
{% load staticfiles %}

<html>

<head>
<title>{% block head_title %}The Fantasy Bakeoff{% endblock head_title %}</title>
<link rel='stylesheet' href='{% static "css/base.css" %}'/>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 
</head>
<style>{% block style %} {% endblock style %}</style>
<body>
<div>
{% include "navbar.html" %}
</div>

<div class="container-fluid text-center">
  <div class="row">
    <div class="col-sm-2">
       </div>
    <div class="col-sm-8">{% block content %}{% endblock content %}
      </div>
    <div class="col-sm-4">
      </div>
  </div>
</div>


<footer class="container-fluid text-center">
  <p><small>Website designed by J Carr</small></p>
</footer>

<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();


      // Store hash
      var hash = this.hash;


      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
  
  $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;


      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });
})
</script>

</body>
</html>

mysite/templates/entry_detail.html
{% extends 'base.html' %}

{% block head_title %}{{Team.user}} | {{block.super}} {% endblock head_title %}


{% block content %}
Welcome to the fantasy bakeoff website. After logging in you can select your team, blah blah.

{% endblock content %}

mysite/templates/howto.html
{% extends 'base.html' %}

{% block content %}
<h2>How to play</h2>
<br>
<b>The concept</b>
<p>It's super simple; you watch the bakeoff and decide on what order you think the bakers are going to be sent home. After the second episode you enter your team, which is simply a ranking of the remaining bakers.</p>
<p>Your fantasy team will be compared to the order Mary and Paul send the bakers home. A score (0-100%)* will determine how well you've correlated with the correct order.</p>
<br>
<b>The Rules</b>
<p>It's pretty self explanatory. But incase of rogue decisions by Paul and Mary, the 'order' the bakers are sent home will be determined by the Wikipedia Bake Off series 7 elimination table order, as determined <a href="https://en.wikipedia.org/wiki/The_Great_British_Bake_Off_(series_7)" target="_blank">here.</a></p>

<br>
<b>The Prize</b><p>
Correct prediction of the entire order will merit a prize. Prize tbc.</p>

<p>You can setup and join leagues to play against friends.</p>
{% if user.is_authenticated %}
<a href="{% url 'fbo:update' %}">Ready to get started - enter a team here</a>
{% else %}
{% include "login.html" %}
{% endif %}
<br><br>
<small>*Negative scores possible if you select the bakers who leave the tent within the first two weeks to be part of your team.</small> 



{% endblock content %}

mysite/templates/league_detail.html
{% extends 'base.html' %}

{% block head_title %}{{league.league}} | {{block.super}} {% endblock head_title %}


{% block content %}
<h3>{{league.league}}</h3><br>
<h4>Share this league number {{league.id}}</h4><br>
<table class="table">
	<thead>
		<tr>
			<th>Team</th>
			<th>Contestant</th>
			<th>Score</th>
		</tr>
	</thead>
	<tbody>
{% for team in league.teams.all %} 
		<tr>
			<td>{{team}}</td>
			<td>{{team.user.first_name}} {{team.user.last_name}}</td>
			<td>{{ team.get_score }}</td>
		</tr>
{% endfor %}
	</tbody>
</table>
{{league.timestamp}}

{% endblock content %}

mysite/templates/league_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Create your own league</h2>
<p>Simply choose a name for your league. A league number will be assigned, by sharing this code others can join your league</p>
<form method='POST' action=''>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create League" />
</form>

{% endblock content %}

mysite/templates/leaguelogin.html
{% extends 'base.html' %}

{% block content %}
<h2>Uh oh, you can't do that yet </h2>
<p>{% if user.is_authenticated %}
To create or join a league you'll need to enter your team first. You can do that <a href="{% url 'fbo:update' %}">here</a>.
{% else %}
To create or join a league you'll need to first login and create a team. <br>
{% include "login.html" %}
{% endif %}
</p>
{% endblock content %}

mysite/templates/logout.html
{% load i18n %}
<!--<h1>{% trans "Sign Out" %}</h1>
<p>{% trans 'Are you sure you want to sign out?' %}</p> -->
<form method="post" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{redirect_field_name}}" value="{{redirect_field_value}}"/>
  {% endif %}
  <button type="submit">{% trans 'Sign Out' %}</button>
</form>

mysite/templates/messages_display.html
{% if messages %}
<ul class="messages">
{% for message in messages %}
<li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
{% endfor %}
</ul>
{% endif %}

mysite/templates/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'fbo:base' %}">The Fantasy Bakeoff</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
	<li><a href="{% url 'posts:howto' %}">How to play</a></li>        
	<!--<li><a href="{% url 'posts:list' %}">Updates</a></li>-->
        {% if user.is_authenticated %}
<li><a href="{% url 'fbo:home' %}">{{user.first_name}}'s Team</a></li>
<li><a href="{% url 'fbo:createLeague' %}">Create League</a></li>
<li><a href="{% url 'fbo:leagueadd' %}">Enter League</a></li>
{% else %}
<li>{% include "login.html" %}</li>
{% endif %}</li>
      </ul>
    </div>
  </div>
</nav>

mysite/templates/post_detail.html
{% extends 'base.html' %}

{% block head_title %}{{instance.title}} | {{block.super}} {% endblock head_title %}


{% block content %}

<br><br>
{{instance.title}}<br>
{{instance.content}}<br>
{{instance.updated}}<br>
{{instance.timestamp}}<br>
{{instance.id}}<br>

{% endblock content %}

mysite/templates/post_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Form</h1>
<form method='POST' action=''>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="create post" />
</form>

{% endblock content %}

mysite/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
<br><br>{% for object in object_list %}
<a href="{{ object.get_absolute_url }}" >{{object.title}}</a><br>
{{object.content}}<br>
{{object.updated}}<br>
{{object.timestamp}}<br>
{{object.id}}<br>
{% endfor %}
{% endblock %}

mysite/templates/team_detail.html
{% extends 'base.html' %}

{% block head_title %}{{user.first_name}} | {{block.super}} {% endblock head_title %}


{% block content %}
<h2><br>{{user.Team.team}}<br></h2>

<h4>Your current selection is shown below. Changes can be made until 8pm BST September 7th 2016.<br></h4>
<table class="table text-left table-condensed">
	<thead>
		<tr>
			<th>Position</th>
			<th>My Prediction</th>
			<th>Result</th>
		<tr>
	</thead>
	<tbody>
		<tr><td>Winner</td><td> {{Team.winner}}</td><td>tbc</td><tr>
		<tr><td>Second</td><td> {{Team.second}}</td><td>tbc</td><tr>
		<tr><td>Third</td><td> {{Team.third}}</td><td>tbc</td><tr>
		<tr><td>Fourth</td><td> {{Team.fourth}}</td><td>tbc</td><tr>
		<tr><td>Fifth</td><td> {{Team.fifth}}</td><td>tbc</td><tr>
		<tr><td>Sixth</td><td> {{Team.sixth}}</td><td>tbc</td><tr>
		<tr><td>Seventh</td><td> {{Team.seventh}}</td><td>tbc</td><tr>
		<tr><td>Eighth</td><td> {{Team.eighth}}</td><td>tbc</td><tr>
		<tr><td>Ninth</td><td> {{Team.ninth}}</td><td>tbc</td><tr>
		<tr><td>Tenth</td><td> {{Team.tenth}}</td><td>tbc</td><tr>
	</tbody>
</table>
<br><h4>
Score: {{Team.get_score }}%<br><br>
To edit your team click <a href="{% url 'fbo:update' %}">here</a>
<br>
Your current leagues are:
<br>{% for league in Leagues %}
<a href="{{ league.get_absolute_url }}" >{{league.league}}</a><br>
{% endfor %}
<br>
To add your team to another league click <a href="{% url 'fbo:leagueadd' %}"> here</a>.
<br>
Or to create your own league click <a href="{% url 'fbo:createLeague' %}"> here</a>.</h4>

{% include "logout.html" %}
{% endblock content %}

mysite/templates/team_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Enter your team</h2>
<p>Choose a team name, select the bakers in your chosen order, then hit submit!<br>
Need a reminder of the contestants - <a HREF="http://www.thegreatbritishbakeoff.co.uk/bakers/series-7/" target="_blank">here's a quick reminder</a>.

</p>

<form method='POST' action=''>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Enter Team" />
</form>

{% endblock content %}